### ISSUE TITLE
Sort maps based on active Map-pool and Team preferences

### ISSUE THREAD

**Issue by Lennyee** [GunnarLuebbermann/my-csmanager-issues#18] opened 2023-10-15 13:39 UTC

**Comment by GunnarLuebbermann** [comment] 2023-10-15 14:39
Duplicate of https://github.com/GunnarLuebbermann/my-csmanager-issues/issues/7

**Comment by jCodin** [comment] 2023-10-17 07:14
fixed

**Closed by jCodin** 2023-10-17 07:14 UTC
Labels: duplicate
